// <auto-generated />
using System;
using JobAssistant.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobAssistant.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200616032238_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JobAssistant.Models.Goal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Amount")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("SoFar");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("GoalId");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("JobAssistant.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ADate")
                        .HasColumnType("Date");

                    b.Property<string>("ClosedNotes")
                        .HasMaxLength(233);

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(27);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Notes")
                        .HasMaxLength(233);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(27);

                    b.Property<DateTime>("RDate")
                        .HasColumnType("Date");

                    b.Property<string>("Status");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobAssistant.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool>("HasGoal");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JobAssistant.Models.Goal", b =>
                {
                    b.HasOne("JobAssistant.Models.User", "Creator")
                        .WithMany("CreatedGoald")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobAssistant.Models.Job", b =>
                {
                    b.HasOne("JobAssistant.Models.User", "Creator")
                        .WithMany("AppliedJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
